spring:
  datasource:
    url: jdbc:mysql://10.0.3.14:3306/eshop
    username: eshop
    password: eshop
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    cluster:
        nodes: 10.0.3.11:7001,10.0.3.11:7002,10.0.3.12:7003,10.0.3.12:7004,10.0.3.13:7005,10.0.3.13:7006
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      tyq:
        eshop:
          inventory:
            mapper: DEBUG